feat: (MSP-11) Initiate git-terminator scripts
gbh-tech/git-cleaner pull request #1
Opened 2024-08-09 20:38 UTC by javiercm1410

2024-08-27 11:41 UTC, angelmadames requested changes

2024-08-27 11:41 UTC, angelmadames commented on .husky/commit-msg
> +. "$(dirname -- "$0")/_/husky.sh"
Not needed in the most recent versions of husky.

2024-08-27 11:41 UTC, angelmadames commented on .tool-versions
> +bun 1.1.21
We should add Renovate to this repo.

2024-08-27 11:41 UTC, angelmadames commented on package.json
> +  "name": "terminator",
We should have the full repository name in here.

2024-08-27 11:41 UTC, angelmadames commented on package.json
> +    "commander": "^12.1.0",
Commander is a production dependency.

2024-08-27 11:41 UTC, angelmadames commented on src/utils/delete_tags.ts
> +import type { Octokit } from "@octokit/core";
In the TypeScript/JavaScript world, file names are `kebak-case` or `camelCase`. `snake_case` is ideal for Python, Go, Ruby, Elixir and others.

2024-08-27 11:41 UTC, angelmadames commented on src/utils/delete_tags.ts
> +// Need test
Avoid unnecessary comments (prefer using `@TODO:` mark).

2024-08-27 11:41 UTC, angelmadames commented on src/utils/delete_tags.ts
> +			});
I know that this appears in the official documentation of GitHub API, but I actually don't like using `.request`. I prefer using `.rest.<method>` for these kind of things. It's more readable and allows you to compose the configuration of all requests elsewhere (ie. defining headerS).

Check these references:
- https://github.com/octokit/octokit.js?tab=readme-ov-file#octokit-api-client
- https://docs.github.com/en/rest/guides/scripting-with-the-rest-api-and-javascript?apiVersion=2022-11-28#using-rest-endpoint-methods-to-make-requests

2024-08-27 11:41 UTC, angelmadames commented on src/utils/delete_tags.ts
> +					// }
Avoid commented code.

2024-08-27 11:41 UTC, angelmadames commented on src/utils/delete_tags.ts
> +				// These console logs are for Testing
These should live elsewhere. Prefer using tests.

2024-08-27 12:12 UTC, javiercm1410 commented on .husky/commit-msg
> +. "$(dirname -- "$0")/_/husky.sh"
Removed!

2024-08-27 12:21 UTC, javiercm1410 commented on .tool-versions
> +bun 1.1.21
Installed and configuration added

2024-08-27 12:23 UTC, javiercm1410 commented on package.json
> +    "commander": "^12.1.0",
installed

2024-08-27 12:24 UTC, javiercm1410 commented on src/utils/delete_tags.ts
> +import type { Octokit } from "@octokit/core";
filename updated

2024-08-27 12:29 UTC, javiercm1410 commented on src/utils/delete_tags.ts
> +// Need test
Comments removed

2024-08-27 14:04 UTC, javiercm1410 commented on package.json
> +  "name": "terminator",
solved

2024-08-27 14:08 UTC, javiercm1410 commented on src/utils/delete_tags.ts
> +					// }
comments removed

2024-08-27 18:21 UTC, javiercm1410 commented on src/utils/delete_tags.ts
> +				// These console logs are for Testing
solved

2024-09-03 13:51 UTC, javiercm1410 commented on command.ts
> +    'Minimum number of Tags to preserve',
Change option description

2024-09-05 12:29 UTC, javiercm1410 commented on src/utils/delete_tags.ts
> +			});
updated!

2024-10-09 15:03 UTC, merged